version: '3.8'

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ull@123
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres-db

  dagster-webserver:
    image: dagster-docker
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
    container_name: dagster-webserver
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/opt/dagster
    volumes:
      - ./dag_test:/opt/dagster/dag_test
    depends_on:
      - postgres-db

  dagster-daemon:
    image: dagster-docker
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster-daemon
    environment:
      - DAGSTER_HOME=/opt/dagster
    volumes:
      - ./dag_test:/opt/dagster/dag_test
    depends_on:
      - postgres-db

volumes:
  postgres_data:
